--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.1.45.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 15.05.2019 18:18:14
-- Server version: 5.6.41
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE task_manager;

--
-- Drop table `comment`
--
DROP TABLE IF EXISTS comment;

--
-- Drop table `discussions`
--
DROP TABLE IF EXISTS discussions;

--
-- Drop table `project_team`
--
DROP TABLE IF EXISTS project_team;

--
-- Drop table `tasks`
--
DROP TABLE IF EXISTS tasks;

--
-- Drop table `tickets`
--
DROP TABLE IF EXISTS tickets;

--
-- Drop table `projects`
--
DROP TABLE IF EXISTS projects;

--
-- Drop table `users`
--
DROP TABLE IF EXISTS users;

--
-- Drop table `comments`
--
DROP TABLE IF EXISTS comments;

--
-- Drop table `project`
--
DROP TABLE IF EXISTS project;

--
-- Drop table `user`
--
DROP TABLE IF EXISTS user;

--
-- Drop table `user_group`
--
DROP TABLE IF EXISTS user_group;

--
-- Set default database
--
USE task_manager;

--
-- Create table `user_group`
--
CREATE TABLE user_group (
  id_group TINYINT(4) UNSIGNED NOT NULL AUTO_INCREMENT,
  groups TINYTEXT NOT NULL,
  PRIMARY KEY (id_group)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `user`
--
CREATE TABLE user (
  id_user INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  username VARCHAR(255) NOT NULL,
  auth_key TINYTEXT NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  password_reset_token VARCHAR(255) DEFAULT NULL,
  email VARCHAR(50) NOT NULL,
  status SMALLINT(6) NOT NULL DEFAULT 10,
  created_at INT(11) NOT NULL,
  updated_at INT(11) NOT NULL,
  id_group INT(11) UNSIGNED DEFAULT NULL,
  fullname VARCHAR(255) DEFAULT NULL,
  photo VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id_user)
)
ENGINE = INNODB,
AUTO_INCREMENT = 4,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create index `email` on table `user`
--
ALTER TABLE user 
  ADD UNIQUE INDEX email(email);

--
-- Create index `password_resset_token` on table `user`
--
ALTER TABLE user 
  ADD UNIQUE INDEX password_resset_token(password_reset_token);

--
-- Create index `username` on table `user`
--
ALTER TABLE user 
  ADD UNIQUE INDEX username(username);

--
-- Create table `project`
--
CREATE TABLE project (
  id_project INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  id_user INT(11) UNSIGNED NOT NULL,
  pr_name TINYTEXT NOT NULL,
  pr_type ENUM('new','support','internal') DEFAULT 'new',
  pr_sratus ENUM('open','on hold','closed','cancelled') NOT NULL DEFAULT 'open',
  pr_desc TEXT NOT NULL,
  pr_update TIMESTAMP NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (id_project)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create foreign key
--
ALTER TABLE project 
  ADD CONSTRAINT FK_project_user_id_user FOREIGN KEY (id_user)
    REFERENCES user(id_user) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `comments`
--
CREATE TABLE comments (
  id_comm INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  id_project INT(11) UNSIGNED NOT NULL,
  id_disc INT(11) DEFAULT NULL,
  id_task INT(11) DEFAULT NULL,
  id_ticket INT(11) DEFAULT NULL,
  text_comm TEXT DEFAULT NULL,
  date TIMESTAMP NULL DEFAULT '0000-00-00 00:00:00',
  id_user INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (id_comm)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create foreign key
--
ALTER TABLE comments 
  ADD CONSTRAINT FK_comments FOREIGN KEY (id_project)
    REFERENCES project(id_project) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE comments 
  ADD CONSTRAINT FK_comments2 FOREIGN KEY (id_user)
    REFERENCES user(id_user) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `users`
--
CREATE TABLE users (
  id_user INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  id_group TINYINT(4) UNSIGNED DEFAULT NULL,
  active TINYINT(1) NOT NULL DEFAULT 1,
  fullname TINYTEXT NOT NULL,
  email TINYTEXT DEFAULT NULL,
  photo TINYTEXT DEFAULT NULL,
  phone TINYTEXT DEFAULT NULL,
  password VARCHAR(255) DEFAULT NULL,
  username VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id_user)
)
ENGINE = INNODB,
AUTO_INCREMENT = 10,
AVG_ROW_LENGTH = 4096,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `projects`
--
CREATE TABLE projects (
  id_project INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  id_user INT(11) UNSIGNED NOT NULL,
  pr_name TINYTEXT NOT NULL,
  pr_type ENUM('new','support','internal') DEFAULT 'new',
  pr_sratus ENUM('open','on hold','closed','cancelled') NOT NULL DEFAULT 'open',
  pr_desc TEXT NOT NULL,
  pr_create TIMESTAMP NULL DEFAULT '0000-00-00 00:00:00',
  rewiew_date DATE DEFAULT NULL,
  design_date DATE DEFAULT NULL,
  devs_date DATE DEFAULT NULL,
  test_date DATE DEFAULT NULL,
  prod_date DATE DEFAULT NULL,
  PRIMARY KEY (id_project)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `tickets`
--
CREATE TABLE tickets (
  id_tickets INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  id_project INT(11) UNSIGNED NOT NULL,
  id_user INT(11) UNSIGNED NOT NULL,
  id_status ENUM('new','closed','cancelled','resolved','fixed') DEFAULT 'new',
  type ENUM('request a change','report a bug','ask a question','raise an issue') DEFAULT NULL,
  subject TINYTEXT NOT NULL,
  ticket_desc TEXT DEFAULT NULL,
  PRIMARY KEY (id_tickets)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create foreign key
--
ALTER TABLE tickets 
  ADD CONSTRAINT FK_tickets_projects_id_project FOREIGN KEY (id_project)
    REFERENCES projects(id_project) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE tickets 
  ADD CONSTRAINT FK_tickets_users_id_user FOREIGN KEY (id_user)
    REFERENCES users(id_user) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `tasks`
--
CREATE TABLE tasks (
  id_task INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  id_user INT(11) UNSIGNED NOT NULL,
  id_project INT(11) UNSIGNED NOT NULL,
  task_name TINYTEXT NOT NULL,
  priority ENUM('low','medium','hight') NOT NULL DEFAULT 'medium',
  task_status ENUM('open','re-open','on hold','completed','cancelled') NOT NULL DEFAULT 'open',
  assigned_to TINYTEXT NOT NULL,
  task_desc TEXT NOT NULL,
  start_date DATE DEFAULT NULL,
  create_date TIMESTAMP NULL DEFAULT '0000-00-00 00:00:00',
  finish_date DATE DEFAULT NULL,
  PRIMARY KEY (id_task)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create foreign key
--
ALTER TABLE tasks 
  ADD CONSTRAINT FK_tasks_projects_id_project FOREIGN KEY (id_project)
    REFERENCES projects(id_project) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE tasks 
  ADD CONSTRAINT FK_tasks_users_id_user FOREIGN KEY (id_user)
    REFERENCES users(id_user) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `project_team`
--
CREATE TABLE project_team (
  id_user INT(11) UNSIGNED NOT NULL,
  id_project INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (id_user, id_project)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create index `id_user` on table `project_team`
--
ALTER TABLE project_team 
  ADD UNIQUE INDEX id_user(id_project);

--
-- Create foreign key
--
ALTER TABLE project_team 
  ADD CONSTRAINT FK_project_team_projects_id_project FOREIGN KEY (id_project)
    REFERENCES projects(id_project) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE project_team 
  ADD CONSTRAINT FK_project_team_users_id_user FOREIGN KEY (id_user)
    REFERENCES users(id_user) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `discussions`
--
CREATE TABLE discussions (
  id_disc INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  id_project INT(11) UNSIGNED NOT NULL,
  id_user INT(11) UNSIGNED NOT NULL,
  id_group TINYINT(4) UNSIGNED NOT NULL,
  disc_name TINYTEXT NOT NULL,
  discription TEXT DEFAULT NULL,
  PRIMARY KEY (id_disc)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create foreign key
--
ALTER TABLE discussions 
  ADD CONSTRAINT FK_discussions_projects_id_project FOREIGN KEY (id_project)
    REFERENCES projects(id_project) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE discussions 
  ADD CONSTRAINT FK_discussions_user_group_id_group FOREIGN KEY (id_group)
    REFERENCES user_group(id_group) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE discussions 
  ADD CONSTRAINT FK_discussions_users_id_user FOREIGN KEY (id_user)
    REFERENCES users(id_user) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `comment`
--
CREATE TABLE comment (
  id_comm INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  id_project INT(11) UNSIGNED NOT NULL,
  id_disc INT(11) DEFAULT NULL,
  id_task INT(11) DEFAULT NULL,
  id_ticket INT(11) DEFAULT NULL,
  text_comm TEXT DEFAULT NULL,
  date TIMESTAMP NULL DEFAULT '0000-00-00 00:00:00',
  id_user INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (id_comm)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create foreign key
--
ALTER TABLE comment 
  ADD CONSTRAINT FK_comment_projects_id_project FOREIGN KEY (id_project)
    REFERENCES projects(id_project) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE comment 
  ADD CONSTRAINT FK_comment_users_id_user FOREIGN KEY (id_user)
    REFERENCES users(id_user) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- 
-- Dumping data for table user_group
--
-- Table task_manager.user_group does not contain any data (it is empty)

-- 
-- Dumping data for table user
--
INSERT INTO user VALUES
(1, 'admin', 'Rxfsr00wqsv1pd84WdWKL_N2dwlAJuue', '$2y$13$d42U3/PBB01Kc9UH.ElLrOfHcGATj7eNyPJBM/oVi6MS3cWpJdM2C', NULL, 'admin@mail.ru\r\n', 10, 1557833188, 1557833188, NULL, NULL, NULL),
(2, 'admin2', 'vPPI3LXvxzxA_Heh6YwRibebUHvXvz9b', '$2y$13$.WxaCi8xMXW7ifvAF1N5Vurfg349VgOQaDe/9nzznat6yaLlZs4hi', '6jTRZRUEhqKpRwNHPyWBvfSC9ilbW1gh_1557845518', 'admin@mail.ru', 10, 1557834010, 1557845518, NULL, NULL, NULL),
(3, 'efsfedgvs', 'C9r_cHo3q-9AVQE_A2EuM2wXexcqSaNW', '$2y$13$Mr07/.VYMOQmdHE/U8S1LumlzFPZPUiJ9pD6C6mRZemk8oqUlDWvu', NULL, 'sdvgesgvsd@knmnkl.ty', 10, 1557839104, 1557839104, NULL, NULL, NULL);

-- 
-- Dumping data for table project
--
-- Table task_manager.project does not contain any data (it is empty)

-- 
-- Dumping data for table users
--
INSERT INTO users VALUES
(4, NULL, 1, '', NULL, NULL, NULL, NULL, NULL),
(5, NULL, 1, '', NULL, NULL, NULL, NULL, NULL),
(6, NULL, 1, '', NULL, NULL, NULL, NULL, NULL),
(7, NULL, 1, '', NULL, NULL, NULL, NULL, NULL),
(8, NULL, 1, '', NULL, NULL, NULL, NULL, NULL),
(9, NULL, 1, '', NULL, NULL, NULL, NULL, NULL);

-- 
-- Dumping data for table projects
--
-- Table task_manager.projects does not contain any data (it is empty)

-- 
-- Dumping data for table tickets
--
-- Table task_manager.tickets does not contain any data (it is empty)

-- 
-- Dumping data for table tasks
--
-- Table task_manager.tasks does not contain any data (it is empty)

-- 
-- Dumping data for table project_team
--
-- Table task_manager.project_team does not contain any data (it is empty)

-- 
-- Dumping data for table discussions
--
-- Table task_manager.discussions does not contain any data (it is empty)

-- 
-- Dumping data for table comments
--
-- Table task_manager.comments does not contain any data (it is empty)

-- 
-- Dumping data for table comment
--
-- Table task_manager.comment does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;